# 1. BUILD Stage: Build the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy csproj and restore dependencies
# Docker Root (JobPortalWebApi) से relative path:
# JobPortalWebApi.csproj, JobPortalWebApi फ़ोल्डर के अंदर है।
COPY ["JobPortalWebApi/JobPortalWebApi.csproj", "JobPortalWebApi/"]
RUN dotnet restore "JobPortalWebApi/JobPortalWebApi.csproj"

# Copy all source code and build
COPY . .
# अब हम उस फ़ोल्डर में जाते हैं जहाँ csproj है
WORKDIR "/src/JobPortalWebApi" 
RUN dotnet publish "JobPortalWebApi.csproj" -c Release -o /app/publish

# 2. FINAL Stage: Create the runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

# Define the entry point for the application
ENTRYPOINT ["dotnet", "JobPortalWebApi.dll"]
